on: 
  push: 
    branches: 
    - master 
    - staging
    - develop 
  pull_request: 
    branches: 
    - master 
    - staging 
    - develop
name: Test build on push
jobs:
  build:
    name: Test go configurations
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
